#
#  Copyright 2015 VMware, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
---
- name: create application directory
  file:
    dest: "/opt/{{ django_app }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: create blackhole directory
  file:
    dest: "/opt/{{ django_app }}/.blackhole"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: recursively sync the ui code from local repos
  become: no
  synchronize:
    src: "../../../ui/"
    dest: "/opt/{{ django_app }}/"
    recursive: yes
    rsync_opts: "--no-motd,--exclude=.git"
    archive: no
    delete: yes
  tags:
    - rsync

- name: create plays directory
  file:
    dest: "/opt/{{ django_app }}-ansible"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: recursively sync the ansible playbooks from local repos
  become: no
  synchronize:
    src: "../../../ansible/playbooks"
    dest: "/opt/{{ django_app }}-ansible/"
    recursive: yes
    rsync_opts:
      - "--no-motd"
      - "--exclude=.git"
    archive: no
    delete: yes
  tags:
    - rsync
    - rsync_ansible_only

- name: recursively sync the ansible roles from local repos
  become: no
  synchronize:
    src: "../../../ansible/roles"
    dest: "/opt/{{ django_app }}-ansible/"
    recursive: yes
    rsync_opts:
      - "--no-motd"
      - "--exclude=.git"
    archive: no
  tags:
    - rsync
    - rsync_ansible_only

- name: recursively sync the ansible library from local repos
  become: no
  synchronize:
    src: "../../../ansible/library"
    dest: "/opt/{{ django_app }}-ansible/"
    recursive: yes
    rsync_opts:
      - "--no-motd"
      - "--exclude=.git"
    archive: no
    delete: yes
  tags:
    - rsync
    - rsync_ansible_only

- name: create application directory
  file:
    dest: "/opt/containers"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: recursively sync the containers built by ansible from local repos
  become: no
  synchronize:
    src: "../../../containers"
    dest: "/opt/"
    recursive: yes
    rsync_opts:
      - "--no-motd"
      - "--exclude=.git"
    archive: no
    delete: yes
  tags:
    - rsync

- name: create playbook execution harnesses and inventory creation scripts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: "0700"
  with_items:
    - { src: 'opt/chaperone-admin_play_tags.j2', dest: '/opt/{{ django_app }}/{{ django_app }}-admin_play_tags' }
    - { src: 'opt/prepare_kubernetes_targets.py.j2', dest: '/opt/{{ django_app }}/prepare_kubernetes_targets.py' }
    - { src: 'opt/prepare_photon_targets.py.j2', dest: '/opt/{{ django_app }}/prepare_photon_targets.py' }
    - { src: 'opt/prepare_variables.py.j2', dest: '/opt/{{ django_app }}/prepare_variables.py' }
  tags:
    - rsync

- name: Create settings.py
  template:
    src: "opt/chaperone/settings.py.j2"
    dest: "/opt/{{ django_app }}/chaperone/settings.py"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
  notify: Restart apache2
  tags:
    - rsync

- name: Create local_settings.py
  template:
    src: "opt/chaperone/local_settings.py.j2"
    dest: "/opt/{{ django_app }}/chaperone/local_settings.py"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
  notify: Restart apache2
  tags:
    - rsync

- name: Create application working directory
  file:
    dest: "/var/lib/{{ django_app }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: Create dummy Chaperone UI base.yml
  command: touch "/var/lib/{{ django_app }}/base.yml"
  args:
    creates: "/var/lib/{{ django_app }}/base.yml"
  become: no
  tags:
    - rsync

- name: Create Answer files directory
  file:
    dest: "{{ chaperone_answer_dir }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: Create Answer file
  command: touch "{{ chaperone_answer_dir }}/answerfile.yml"
  args:
    creates: "{{ chaperone_answer_dir }}/answerfile.yml"
  become: no

- name: Create Prepare files directory
  file:
    dest: "{{ chaperone_prepare_files_dir }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: Create Logs directory
  file:
    dest: "{{ chaperone_log_dir }}"
    state: directory
    owner: "root"
    group: "{{ ansible_ssh_user }}"
    mode: 0775
  tags:
    - rsync

- name: Create Logs directory
  file:
    dest: "{{ chaperone_log_dir }}/{{ django_app }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
  tags:
    - rsync

- name: Create database
  command: touch "/opt/{{ django_app }}/{{ django_app }}.db"
  args:
    creates: "/opt/{{ django_app }}/{{ django_app }}.db"
  become: no
  register: db
  tags:
    - db
    - rsync

# Stat the db and if zero sized, rebuild it because either
# the above 'touch' created it, or someone else truncated it.
# either way, have to rebuild it.
- name: Stat the database to determine if it's truncated to zero
  stat: path="/opt/{{ django_app }}/{{ django_app }}.db" get_checksum=no get_md5=no
  when: not db.changed
  register: dbstat
  tags:
    - db
    - rsync

- name: Initialize database
  command: python manage.py syncdb --noinput
  args:
    chdir: "/opt/{{ django_app }}"
  become: no
  when: db.changed or dbstat.stat.size == 0
  tags:
    - db
    - rsync

- name: (Re)Generate site-available ui config
  template:
    src: "etc/apache2/sites-available/chaperone.conf.j2"
    dest: "/etc/apache2/sites-available/{{ django_app }}.conf"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0644
  tags:
    - rsync

- name: (Re)Generate site-available download config
  template:
    src: "etc/apache2/sites-available/chaperone-downloads.conf.j2"
    dest: "/etc/apache2/sites-available/{{ django_app }}-downloads.conf"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0644
  tags:
    - downloads

- name: Disable 000-default site
  command: a2dissite 000-default
  notify: Restart apache2
  tags:
    - rsync

- name: Enable application site
  command: a2ensite {{ django_app }}
  notify: Restart apache2
  tags:
    - rsync

- name: Enable the general application site (this is not the ui)
  command: "a2ensite {{ django_app }}-downloads"
  notify: Restart apache2
  tags:
    - downloads
